# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Celtson Toote's Personal Website
email: celtson.toote@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Celtson Toote's personal website portfolio. Here I have
  information about myself, and samples of some of my current work.
  These work range from website design to web devlopment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://celtson.com" # the base hostname & protocol for your site
github_username: ct1221
image: /img/og-home.png

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-58112357-2

# Social SEO Tags
plugins:
  - jekyll-seo-tag
